### PR TITLE
pls review my code

### PR DESCRIPTION
**Pull request by giri-x**

### CODE REVIEW

**Comment by giri-x** [comment]
[MicroServices.pdf](https://github.com/user-attachments/files/16071436/MicroServices.pdf)

**Comment by aravindpandiyarajan2004** [comment]
It's doesn't maintain the code quality.
[CodeQualityReport.pdf](https://github.com/user-attachments/files/16071445/CodeQualityReport.pdf)

**Review by Velan483 — APPROVED** [review]

**Review by aravindpandiyarajan2004 — APPROVED** [review]
pls change as per the mentioned in the doc.

**Comment by giri-x** [comment]
thanks

**Pull request merged**
